// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0090:Usar 'new(...)'", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroCliente.buttonExcluirCadastroCliente_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE0090:Usar 'new(...)'", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroFuncionario.SearchFuncionario")]
[assembly: SuppressMessage("Usage", "CA2211:Campos não constantes não devem ser visíveis", Justification = "<Pendente>", Scope = "member", Target = "~F:PizzariaDoZe.CustomMessageBox.result")]
[assembly: SuppressMessage("Style", "IDE0044:Adicionar modificador somente leitura", Justification = "<Pendente>", Scope = "member", Target = "~F:PizzariaDoZe.Login.txtAbout")]
[assembly: SuppressMessage("Style", "IDE0044:Adicionar modificador somente leitura", Justification = "<Pendente>", Scope = "member", Target = "~F:PizzariaDoZe.Login.txtAboutMessage")]
[assembly: SuppressMessage("Style", "IDE0044:Adicionar modificador somente leitura", Justification = "<Pendente>", Scope = "member", Target = "~F:PizzariaDoZe.Login.txtContinue")]
[assembly: SuppressMessage("Style", "IDE0044:Adicionar modificador somente leitura", Justification = "<Pendente>", Scope = "member", Target = "~F:PizzariaDoZe.Login.txtExit")]
[assembly: SuppressMessage("Style", "IDE0044:Adicionar modificador somente leitura", Justification = "<Pendente>", Scope = "member", Target = "~F:PizzariaDoZe.Login.txtMessage")]
[assembly: SuppressMessage("Style", "IDE0044:Adicionar modificador somente leitura", Justification = "<Pendente>", Scope = "member", Target = "~F:PizzariaDoZe.Login.txtOpenApplicaton")]
[assembly: SuppressMessage("Style", "IDE0044:Adicionar modificador somente leitura", Justification = "<Pendente>", Scope = "member", Target = "~F:PizzariaDoZe.Login.txtSendToTray")]
[assembly: SuppressMessage("Style", "IDE0044:Adicionar modificador somente leitura", Justification = "<Pendente>", Scope = "member", Target = "~F:PizzariaDoZe.utils.Funcoes.controldefaults")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroCliente.buttonEditarCadastroCliente_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroCliente.buttonExcluirCadastroCliente_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroCliente.buttonFecharCadastroCliente_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroCliente.buttonPesquisaCadastroIngredientes_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroCliente.buttonSalvarCadastroCliente_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroCliente.checkKeyDown(System.Object,System.Windows.Forms.KeyEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroCliente.cleanForm")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroCliente.cleanFormAndUpdateList")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroCliente.createCliente~PizzariaDoZe.DAO.Cliente")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroCliente.maskedTextBoxCepCadastroCliente_Leave(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE0059:Atribuição desnecessária de um valor", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroCliente.ValidForm~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroFuncionario.buttonEditarCadastroFuncionario_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroFuncionario.buttonExcluirCadastroFuncionario_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroFuncionario.buttonFecharCadastroFuncionario_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroFuncionario.buttonPesquisaCadastroIngredientes_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroFuncionario.buttonSalvarCadastroFuncionario_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroFuncionario.checkKeyDown(System.Object,System.Windows.Forms.KeyEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroFuncionario.cleanForm")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroFuncionario.cleanFormAndUpdateList")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroFuncionario.createFuncionario~PizzariaDoZe.DAO.Funcionario")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroIngredientes.buttonEditarCadastroIngrediente_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroIngredientes.buttonExcluirCadastroIngrediente_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroIngredientes.buttonFecharCadastroIngrediente_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroIngredientes.buttonPesquisaCadastroIngredientes_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroIngredientes.buttonSalvarCadastroIngrediente_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroIngredientes.checkKeyDown(System.Object,System.Windows.Forms.KeyEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroIngredientes.cleanForm")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroIngredientes.cleanFormAndUpdateList")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroIngredientes.fillGrid(System.Data.DataTable)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroIngredientes.labelIngredientesCadastroIngredientes_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroLogradouro.buttonFecharCadastroLogradouro_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroLogradouro.buttonPesquisaCadastroIngredientes_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroLogradouro.checkKeyDown(System.Object,System.Windows.Forms.KeyEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroProduto.buttonFecharCadastroProduto_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroProduto.checkKeyDown(System.Object,System.Windows.Forms.KeyEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroSabor.buttonFecharCadastroSabor_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroSabor.checkKeyDown(System.Object,System.Windows.Forms.KeyEventArgs)")]
[assembly: SuppressMessage("Style", "IDE0063:Usar a instrução 'using' simples", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroSabor.PictureBox1_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroValor.buttonFecharCadastroValor_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CadastroValor.checkKeyDown(System.Object,System.Windows.Forms.KeyEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.Configuracoes.buttonFecharConfig_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.Configuracoes.comboBoxIdiomaConfig_SelectedValueChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CustomMessageBox.buttonContinue_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CustomMessageBox.buttonExit_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.CustomMessageBox.buttonTray_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.Login.buttonLogin_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.Login.checkKeyDown(System.Object,System.Windows.Forms.KeyEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.Login.closeSystemTray(System.Boolean)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.Login.comboBoxIdiomaLogin_SelectedValueChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.Login.configureMenuStrip")]
[assembly: SuppressMessage("Performance", "CA1822:Marcar membros como estáticos", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.Login.Convert(System.Object)~System.Drawing.Point")]
[assembly: SuppressMessage("Performance", "CA1829:Usar a propriedade Length/Count em vez de Count() quando disponível", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.utils.EnumExtensions.GetDescription(System.Enum)~System.String")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.utils.Funcoes.configComboBox(System.Windows.Forms.ComboBox)")]
[assembly: SuppressMessage("Style", "IDE1006:Estilos de Nomenclatura", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.utils.Funcoes.getControlPath(System.Windows.Forms.Control)~System.Windows.Forms.Form")]
[assembly: SuppressMessage("Performance", "CA1850:Preferir o método estático “HashData” em vez de “ComputeHash”", Justification = "<Pendente>", Scope = "member", Target = "~M:PizzariaDoZe.utils.Funcoes.Sha256Hash(System.String)~System.String")]
