//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzariaDoZe.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_en_US() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PizzariaDoZe.Properties.Resources-en-US", typeof(Resources_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Customer registration.
        /// </summary>
        internal static string buttonCadastroClienteLink_Text {
            get {
                return ResourceManager.GetString("buttonCadastroClienteLink.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Employee registration.
        /// </summary>
        internal static string buttonCadastroFuncionarioLink_Text {
            get {
                return ResourceManager.GetString("buttonCadastroFuncionarioLink.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ingredient register.
        /// </summary>
        internal static string buttonCadastroIngredienteLink_Text {
            get {
                return ResourceManager.GetString("buttonCadastroIngredienteLink.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Public Settler Registration.
        /// </summary>
        internal static string buttonCadastroLogradouroLink_Text {
            get {
                return ResourceManager.GetString("buttonCadastroLogradouroLink.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Product registration.
        /// </summary>
        internal static string buttonCadastroProdutoLink_Text {
            get {
                return ResourceManager.GetString("buttonCadastroProdutoLink.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sabor registration.
        /// </summary>
        internal static string buttonCadastroSaborLink_Text {
            get {
                return ResourceManager.GetString("buttonCadastroSaborLink.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Value Registration.
        /// </summary>
        internal static string buttonCadastroValorLink_Text {
            get {
                return ResourceManager.GetString("buttonCadastroValorLink.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Edit.
        /// </summary>
        internal static string buttonEditarCadastroCliente_Text {
            get {
                return ResourceManager.GetString("buttonEditarCadastroCliente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Edit.
        /// </summary>
        internal static string buttonEditarCadastroFuncionario_Text {
            get {
                return ResourceManager.GetString("buttonEditarCadastroFuncionario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Edit.
        /// </summary>
        internal static string buttonEditarCadastroLogradouro_Text {
            get {
                return ResourceManager.GetString("buttonEditarCadastroLogradouro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Edit.
        /// </summary>
        internal static string buttonEditarCadastroProduto_Text {
            get {
                return ResourceManager.GetString("buttonEditarCadastroProduto.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Edit.
        /// </summary>
        internal static string buttonEditarCadastroSabor_Text {
            get {
                return ResourceManager.GetString("buttonEditarCadastroSabor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Edit.
        /// </summary>
        internal static string buttonEditarCadastroValor_Text {
            get {
                return ResourceManager.GetString("buttonEditarCadastroValor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delete.
        /// </summary>
        internal static string buttonExcluirCadastroCliente_Text {
            get {
                return ResourceManager.GetString("buttonExcluirCadastroCliente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delete.
        /// </summary>
        internal static string buttonExcluirCadastroFuncionario_Text {
            get {
                return ResourceManager.GetString("buttonExcluirCadastroFuncionario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delete.
        /// </summary>
        internal static string buttonExcluirCadastroLogradouro_Text {
            get {
                return ResourceManager.GetString("buttonExcluirCadastroLogradouro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delete.
        /// </summary>
        internal static string buttonExcluirCadastroProduto_Text {
            get {
                return ResourceManager.GetString("buttonExcluirCadastroProduto.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delete.
        /// </summary>
        internal static string buttonExcluirCadastroSabor_Text {
            get {
                return ResourceManager.GetString("buttonExcluirCadastroSabor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delete.
        /// </summary>
        internal static string buttonExcluirCadastroValor_Text {
            get {
                return ResourceManager.GetString("buttonExcluirCadastroValor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Close.
        /// </summary>
        internal static string buttonFecharCadastroCliente_Text {
            get {
                return ResourceManager.GetString("buttonFecharCadastroCliente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Close.
        /// </summary>
        internal static string buttonFecharCadastroFuncionario_Text {
            get {
                return ResourceManager.GetString("buttonFecharCadastroFuncionario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Close.
        /// </summary>
        internal static string buttonFecharCadastroLogradouro_Text {
            get {
                return ResourceManager.GetString("buttonFecharCadastroLogradouro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Close.
        /// </summary>
        internal static string buttonFecharCadastroProduto_Text {
            get {
                return ResourceManager.GetString("buttonFecharCadastroProduto.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Close.
        /// </summary>
        internal static string buttonFecharCadastroSabor_Text {
            get {
                return ResourceManager.GetString("buttonFecharCadastroSabor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Close.
        /// </summary>
        internal static string buttonFecharCadastroValor_Text {
            get {
                return ResourceManager.GetString("buttonFecharCadastroValor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login.
        /// </summary>
        internal static string buttonLogin_Text {
            get {
                return ResourceManager.GetString("buttonLogin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logout.
        /// </summary>
        internal static string buttonLogout_Text {
            get {
                return ResourceManager.GetString("buttonLogout.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save.
        /// </summary>
        internal static string buttonSalvarCadastroCliente_Text {
            get {
                return ResourceManager.GetString("buttonSalvarCadastroCliente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save.
        /// </summary>
        internal static string buttonSalvarCadastroFuncionario_Text {
            get {
                return ResourceManager.GetString("buttonSalvarCadastroFuncionario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save.
        /// </summary>
        internal static string buttonSalvarCadastroLogradouro_Text {
            get {
                return ResourceManager.GetString("buttonSalvarCadastroLogradouro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save.
        /// </summary>
        internal static string buttonSalvarCadastroProduto_Text {
            get {
                return ResourceManager.GetString("buttonSalvarCadastroProduto.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save.
        /// </summary>
        internal static string buttonSalvarCadastroSabor_Text {
            get {
                return ResourceManager.GetString("buttonSalvarCadastroSabor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save.
        /// </summary>
        internal static string buttonSalvarCadastroValor_Text {
            get {
                return ResourceManager.GetString("buttonSalvarCadastroValor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Neighborhood.
        /// </summary>
        internal static string labelBairro_Text {
            get {
                return ResourceManager.GetString("labelBairro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Driver&apos;s license.
        /// </summary>
        internal static string labelCarteiraMotorista_Text {
            get {
                return ResourceManager.GetString("labelCarteiraMotorista.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Category.
        /// </summary>
        internal static string labelCategoria_Text {
            get {
                return ResourceManager.GetString("labelCategoria.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Zip code.
        /// </summary>
        internal static string labelCep_Text {
            get {
                return ResourceManager.GetString("labelCep.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a City.
        /// </summary>
        internal static string labelCidade_Text {
            get {
                return ResourceManager.GetString("labelCidade.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Complement.
        /// </summary>
        internal static string labelComplemento_Text {
            get {
                return ResourceManager.GetString("labelComplemento.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF.
        /// </summary>
        internal static string labelCpf_Text {
            get {
                return ResourceManager.GetString("labelCpf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail.
        /// </summary>
        internal static string labelEmail_Text {
            get {
                return ResourceManager.GetString("labelEmail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Photo (242x242).
        /// </summary>
        internal static string labelFoto242x242_Text {
            get {
                return ResourceManager.GetString("labelFoto242x242.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Public place.
        /// </summary>
        internal static string labelLogradouro_Text {
            get {
                return ResourceManager.GetString("labelLogradouro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registration.
        /// </summary>
        internal static string labelMatricula_Text {
            get {
                return ResourceManager.GetString("labelMatricula.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ML.
        /// </summary>
        internal static string labelMl_Text {
            get {
                return ResourceManager.GetString("labelMl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name.
        /// </summary>
        internal static string labelNome_Text {
            get {
                return ResourceManager.GetString("labelNome.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Number.
        /// </summary>
        internal static string labelNumero_Text {
            get {
                return ResourceManager.GetString("labelNumero.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Observation.
        /// </summary>
        internal static string labelObservacao_Text {
            get {
                return ResourceManager.GetString("labelObservacao.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Country.
        /// </summary>
        internal static string labelPais_Text {
            get {
                return ResourceManager.GetString("labelPais.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password.
        /// </summary>
        internal static string labelSenha_Text {
            get {
                return ResourceManager.GetString("labelSenha.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Size.
        /// </summary>
        internal static string labelTamanho_Text {
            get {
                return ResourceManager.GetString("labelTamanho.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telephone.
        /// </summary>
        internal static string labelTelefone_Text {
            get {
                return ResourceManager.GetString("labelTelefone.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Type.
        /// </summary>
        internal static string labelTipo_Text {
            get {
                return ResourceManager.GetString("labelTipo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Customer registration.
        /// </summary>
        internal static string labelTitleCadastroCliente_Text {
            get {
                return ResourceManager.GetString("labelTitleCadastroCliente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Employee registration.
        /// </summary>
        internal static string labelTitleCadastroFuncionario_Text {
            get {
                return ResourceManager.GetString("labelTitleCadastroFuncionario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Public Settler Registration.
        /// </summary>
        internal static string labelTitleCadastroLogradouro_Text {
            get {
                return ResourceManager.GetString("labelTitleCadastroLogradouro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Product registration.
        /// </summary>
        internal static string labelTitleCadastroProduto_Text {
            get {
                return ResourceManager.GetString("labelTitleCadastroProduto.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sabor registration.
        /// </summary>
        internal static string labelTitleCadastroSabor_Text {
            get {
                return ResourceManager.GetString("labelTitleCadastroSabor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Value Registration.
        /// </summary>
        internal static string labelTitleCadastroValor_Text {
            get {
                return ResourceManager.GetString("labelTitleCadastroValor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UF.
        /// </summary>
        internal static string labelUf_Text {
            get {
                return ResourceManager.GetString("labelUf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Validity.
        /// </summary>
        internal static string labelValidade_Text {
            get {
                return ResourceManager.GetString("labelValidade.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Value.
        /// </summary>
        internal static string labelValor_Text {
            get {
                return ResourceManager.GetString("labelValor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Border value.
        /// </summary>
        internal static string labelValorBorda_Text {
            get {
                return ResourceManager.GetString("labelValorBorda.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a teste.
        /// </summary>
        internal static string msgLogin {
            get {
                return ResourceManager.GetString("msgLogin", resourceCulture);
            }
        }
    }
}
