//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzariaDoZe.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PizzariaDoZe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addImagem {
            get {
                object obj = ResourceManager.GetObject("addImagem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de Cliente.
        /// </summary>
        internal static string buttonCadastroClienteLink_Text {
            get {
                return ResourceManager.GetString("buttonCadastroClienteLink.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de Funcionário.
        /// </summary>
        internal static string buttonCadastroFuncionarioLink_Text {
            get {
                return ResourceManager.GetString("buttonCadastroFuncionarioLink.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de Ingrediente.
        /// </summary>
        internal static string buttonCadastroIngredienteLink_Text {
            get {
                return ResourceManager.GetString("buttonCadastroIngredienteLink.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de Logradouro.
        /// </summary>
        internal static string buttonCadastroLogradouroLink_Text {
            get {
                return ResourceManager.GetString("buttonCadastroLogradouroLink.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de Produto.
        /// </summary>
        internal static string buttonCadastroProdutoLink_Text {
            get {
                return ResourceManager.GetString("buttonCadastroProdutoLink.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de Sabor.
        /// </summary>
        internal static string buttonCadastroSaborLink_Text {
            get {
                return ResourceManager.GetString("buttonCadastroSaborLink.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de Valor.
        /// </summary>
        internal static string buttonCadastroValorLink_Text {
            get {
                return ResourceManager.GetString("buttonCadastroValorLink.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configurações.
        /// </summary>
        internal static string buttonConfiguracoesLink_Text {
            get {
                return ResourceManager.GetString("buttonConfiguracoesLink.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar.
        /// </summary>
        internal static string buttonEditarCadastroCliente_Text {
            get {
                return ResourceManager.GetString("buttonEditarCadastroCliente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar.
        /// </summary>
        internal static string buttonEditarCadastroFuncionario_Text {
            get {
                return ResourceManager.GetString("buttonEditarCadastroFuncionario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar.
        /// </summary>
        internal static string buttonEditarCadastroLogradouro_Text {
            get {
                return ResourceManager.GetString("buttonEditarCadastroLogradouro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar.
        /// </summary>
        internal static string buttonEditarCadastroProduto_Text {
            get {
                return ResourceManager.GetString("buttonEditarCadastroProduto.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar.
        /// </summary>
        internal static string buttonEditarCadastroSabor_Text {
            get {
                return ResourceManager.GetString("buttonEditarCadastroSabor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar.
        /// </summary>
        internal static string buttonEditarCadastroValor_Text {
            get {
                return ResourceManager.GetString("buttonEditarCadastroValor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir.
        /// </summary>
        internal static string buttonExcluirCadastroCliente_Text {
            get {
                return ResourceManager.GetString("buttonExcluirCadastroCliente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir.
        /// </summary>
        internal static string buttonExcluirCadastroFuncionario_Text {
            get {
                return ResourceManager.GetString("buttonExcluirCadastroFuncionario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir.
        /// </summary>
        internal static string buttonExcluirCadastroLogradouro_Text {
            get {
                return ResourceManager.GetString("buttonExcluirCadastroLogradouro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir.
        /// </summary>
        internal static string buttonExcluirCadastroProduto_Text {
            get {
                return ResourceManager.GetString("buttonExcluirCadastroProduto.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir.
        /// </summary>
        internal static string buttonExcluirCadastroSabor_Text {
            get {
                return ResourceManager.GetString("buttonExcluirCadastroSabor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir.
        /// </summary>
        internal static string buttonExcluirCadastroValor_Text {
            get {
                return ResourceManager.GetString("buttonExcluirCadastroValor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fechar.
        /// </summary>
        internal static string buttonFecharCadastroCliente_Text {
            get {
                return ResourceManager.GetString("buttonFecharCadastroCliente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fechar.
        /// </summary>
        internal static string buttonFecharCadastroFuncionario_Text {
            get {
                return ResourceManager.GetString("buttonFecharCadastroFuncionario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fechar.
        /// </summary>
        internal static string buttonFecharCadastroLogradouro_Text {
            get {
                return ResourceManager.GetString("buttonFecharCadastroLogradouro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fechar.
        /// </summary>
        internal static string buttonFecharCadastroProduto_Text {
            get {
                return ResourceManager.GetString("buttonFecharCadastroProduto.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fechar.
        /// </summary>
        internal static string buttonFecharCadastroSabor_Text {
            get {
                return ResourceManager.GetString("buttonFecharCadastroSabor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fechar.
        /// </summary>
        internal static string buttonFecharCadastroValor_Text {
            get {
                return ResourceManager.GetString("buttonFecharCadastroValor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fechar.
        /// </summary>
        internal static string buttonFecharConfig_Text {
            get {
                return ResourceManager.GetString("buttonFecharConfig.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Entrar.
        /// </summary>
        internal static string buttonLogin_Text {
            get {
                return ResourceManager.GetString("buttonLogin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sair.
        /// </summary>
        internal static string buttonLogout_Text {
            get {
                return ResourceManager.GetString("buttonLogout.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        internal static string buttonSalvarCadastroCliente_Text {
            get {
                return ResourceManager.GetString("buttonSalvarCadastroCliente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        internal static string buttonSalvarCadastroFuncionario_Text {
            get {
                return ResourceManager.GetString("buttonSalvarCadastroFuncionario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        internal static string buttonSalvarCadastroLogradouro_Text {
            get {
                return ResourceManager.GetString("buttonSalvarCadastroLogradouro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        internal static string buttonSalvarCadastroProduto_Text {
            get {
                return ResourceManager.GetString("buttonSalvarCadastroProduto.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        internal static string buttonSalvarCadastroSabor_Text {
            get {
                return ResourceManager.GetString("buttonSalvarCadastroSabor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        internal static string buttonSalvarCadastroValor_Text {
            get {
                return ResourceManager.GetString("buttonSalvarCadastroValor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancelicon {
            get {
                object obj = ResourceManager.GetObject("cancelicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cliente {
            get {
                object obj = ResourceManager.GetObject("cliente", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap config {
            get {
                object obj = ResourceManager.GetObject("config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deleteicon {
            get {
                object obj = ResourceManager.GetObject("deleteicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap editicon {
            get {
                object obj = ResourceManager.GetObject("editicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap funcionarios {
            get {
                object obj = ResourceManager.GetObject("funcionarios", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ingrediente {
            get {
                object obj = ResourceManager.GetObject("ingrediente", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bairro.
        /// </summary>
        internal static string labelBairro_Text {
            get {
                return ResourceManager.GetString("labelBairro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Carteira de Motorista.
        /// </summary>
        internal static string labelCarteiraMotorista_Text {
            get {
                return ResourceManager.GetString("labelCarteiraMotorista.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria.
        /// </summary>
        internal static string labelCategoria_Text {
            get {
                return ResourceManager.GetString("labelCategoria.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CEP.
        /// </summary>
        internal static string labelCep_Text {
            get {
                return ResourceManager.GetString("labelCep.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cidade.
        /// </summary>
        internal static string labelCidade_Text {
            get {
                return ResourceManager.GetString("labelCidade.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Complemento.
        /// </summary>
        internal static string labelComplemento_Text {
            get {
                return ResourceManager.GetString("labelComplemento.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF.
        /// </summary>
        internal static string labelCpf_Text {
            get {
                return ResourceManager.GetString("labelCpf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail.
        /// </summary>
        internal static string labelEmail_Text {
            get {
                return ResourceManager.GetString("labelEmail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Foto (242x242).
        /// </summary>
        internal static string labelFoto242x242_Text {
            get {
                return ResourceManager.GetString("labelFoto242x242.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Idioma.
        /// </summary>
        internal static string labelIdioma_Text {
            get {
                return ResourceManager.GetString("labelIdioma.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logradouro.
        /// </summary>
        internal static string labelLogradouro_Text {
            get {
                return ResourceManager.GetString("labelLogradouro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Matrícula.
        /// </summary>
        internal static string labelMatricula_Text {
            get {
                return ResourceManager.GetString("labelMatricula.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ML.
        /// </summary>
        internal static string labelMl_Text {
            get {
                return ResourceManager.GetString("labelMl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        internal static string labelNome_Text {
            get {
                return ResourceManager.GetString("labelNome.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número.
        /// </summary>
        internal static string labelNumero_Text {
            get {
                return ResourceManager.GetString("labelNumero.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Observação.
        /// </summary>
        internal static string labelObservacao_Text {
            get {
                return ResourceManager.GetString("labelObservacao.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a País.
        /// </summary>
        internal static string labelPais_Text {
            get {
                return ResourceManager.GetString("labelPais.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        internal static string labelSenha_Text {
            get {
                return ResourceManager.GetString("labelSenha.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tamanho.
        /// </summary>
        internal static string labelTamanho_Text {
            get {
                return ResourceManager.GetString("labelTamanho.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone.
        /// </summary>
        internal static string labelTelefone_Text {
            get {
                return ResourceManager.GetString("labelTelefone.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo.
        /// </summary>
        internal static string labelTipo_Text {
            get {
                return ResourceManager.GetString("labelTipo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de Cliente.
        /// </summary>
        internal static string labelTitleCadastroCliente_Text {
            get {
                return ResourceManager.GetString("labelTitleCadastroCliente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de Funcionário.
        /// </summary>
        internal static string labelTitleCadastroFuncionario_Text {
            get {
                return ResourceManager.GetString("labelTitleCadastroFuncionario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de Logradouro.
        /// </summary>
        internal static string labelTitleCadastroLogradouro_Text {
            get {
                return ResourceManager.GetString("labelTitleCadastroLogradouro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de Produto.
        /// </summary>
        internal static string labelTitleCadastroProduto_Text {
            get {
                return ResourceManager.GetString("labelTitleCadastroProduto.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de Sabor.
        /// </summary>
        internal static string labelTitleCadastroSabor_Text {
            get {
                return ResourceManager.GetString("labelTitleCadastroSabor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de Valor.
        /// </summary>
        internal static string labelTitleCadastroValor_Text {
            get {
                return ResourceManager.GetString("labelTitleCadastroValor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configurações.
        /// </summary>
        internal static string labelTitleConfiguracoes_Text {
            get {
                return ResourceManager.GetString("labelTitleConfiguracoes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UF.
        /// </summary>
        internal static string labelUf_Text {
            get {
                return ResourceManager.GetString("labelUf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Validade.
        /// </summary>
        internal static string labelValidade_Text {
            get {
                return ResourceManager.GetString("labelValidade.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor.
        /// </summary>
        internal static string labelValor_Text {
            get {
                return ResourceManager.GetString("labelValor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor da Borda.
        /// </summary>
        internal static string labelValorBorda_Text {
            get {
                return ResourceManager.GetString("labelValorBorda.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logout {
            get {
                object obj = ResourceManager.GetObject("logout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logoZe {
            get {
                object obj = ResourceManager.GetObject("logoZe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logoZe_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("logoZe-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logradouro {
            get {
                object obj = ResourceManager.GetObject("logradouro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pizza {
            get {
                object obj = ResourceManager.GetObject("pizza", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pizza_slice_solid {
            get {
                object obj = ResourceManager.GetObject("pizza-slice-solid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap product {
            get {
                object obj = ResourceManager.GetObject("product", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap product_2652218 {
            get {
                object obj = ResourceManager.GetObject("product_2652218", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sabor {
            get {
                object obj = ResourceManager.GetObject("sabor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sabor1 {
            get {
                object obj = ResourceManager.GetObject("sabor1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap saveicon {
            get {
                object obj = ResourceManager.GetObject("saveicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Idioma.
        /// </summary>
        internal static string tabPageIdioma_Text {
            get {
                return ResourceManager.GetString("tabPageIdioma.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sobre.
        /// </summary>
        internal static string txtAbout {
            get {
                return ResourceManager.GetString("txtAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pastelaria do Zé v1.0.
        /// </summary>
        internal static string txtAboutMessage {
            get {
                return ResourceManager.GetString("txtAboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atenção.
        /// </summary>
        internal static string txtAttention {
            get {
                return ResourceManager.GetString("txtAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cliente já adicionado!.
        /// </summary>
        internal static string txtClientAlreadyAdd {
            get {
                return ResourceManager.GetString("txtClientAlreadyAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você tem certeza que deseja fechar o programa?.
        /// </summary>
        internal static string txtCloseProgramQuestion {
            get {
                return ResourceManager.GetString("txtCloseProgramQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Continuar.
        /// </summary>
        internal static string txtContinue {
            get {
                return ResourceManager.GetString("txtContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dados excluidos com sucesso!.
        /// </summary>
        internal static string txtDataDeleteWithSuccess {
            get {
                return ResourceManager.GetString("txtDataDeleteWithSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dados editados com sucesso!.
        /// </summary>
        internal static string txtDataEditWithSuccess {
            get {
                return ResourceManager.GetString("txtDataEditWithSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dados inseridos com sucesso.
        /// </summary>
        internal static string txtDataInsertWithSuccess {
            get {
                return ResourceManager.GetString("txtDataInsertWithSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione um cliente!.
        /// </summary>
        internal static string txtDataSelectOneClient {
            get {
                return ResourceManager.GetString("txtDataSelectOneClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione um funcionário!.
        /// </summary>
        internal static string txtDataSelectOneEmployee {
            get {
                return ResourceManager.GetString("txtDataSelectOneEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione um funcionário e endereço valido!.
        /// </summary>
        internal static string txtDataSelectOneEmployeeAndAddress {
            get {
                return ResourceManager.GetString("txtDataSelectOneEmployeeAndAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Funcionário já adicionado!.
        /// </summary>
        internal static string txtEmployeeAlreadyAdd {
            get {
                return ResourceManager.GetString("txtEmployeeAlreadyAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sair.
        /// </summary>
        internal static string txtExit {
            get {
                return ResourceManager.GetString("txtExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Preencha o nome do ingrediente.
        /// </summary>
        internal static string txtFillIngredientName {
            get {
                return ResourceManager.GetString("txtFillIngredientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este ingrediente já está adicionado.
        /// </summary>
        internal static string txtIngredientAlreadyAdd {
            get {
                return ResourceManager.GetString("txtIngredientAlreadyAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você tem certeza que deseja sair?.
        /// </summary>
        internal static string txtLogoutQuestion {
            get {
                return ResourceManager.GetString("txtLogoutQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Abrir Aplicação.
        /// </summary>
        internal static string txtOpenApplication {
            get {
                return ResourceManager.GetString("txtOpenApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Realmente deseja excluir esse cliente?.
        /// </summary>
        internal static string txtQuestionDeleteClient {
            get {
                return ResourceManager.GetString("txtQuestionDeleteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Realmente deseja excluir esse funcionário?.
        /// </summary>
        internal static string txtQuestionDeleteEmployee {
            get {
                return ResourceManager.GetString("txtQuestionDeleteEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Realmente deseja excluir esse ingrediente?.
        /// </summary>
        internal static string txtQuestionDeleteIngredient {
            get {
                return ResourceManager.GetString("txtQuestionDeleteIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione um cliente para editar!.
        /// </summary>
        internal static string txtSelectClientToEdit {
            get {
                return ResourceManager.GetString("txtSelectClientToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione um funcionário para editar!.
        /// </summary>
        internal static string txtSelectEmployeeToEdit {
            get {
                return ResourceManager.GetString("txtSelectEmployeeToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione um grupo!.
        /// </summary>
        internal static string txtSelectGroup {
            get {
                return ResourceManager.GetString("txtSelectGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione um ingrediente!.
        /// </summary>
        internal static string txtSelectIngredient {
            get {
                return ResourceManager.GetString("txtSelectIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione um ingrediente para editar.
        /// </summary>
        internal static string txtSelectIngredientToEdit {
            get {
                return ResourceManager.GetString("txtSelectIngredientToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione um endereço valido!.
        /// </summary>
        internal static string txtSelectValidAddress {
            get {
                return ResourceManager.GetString("txtSelectValidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bandeja.
        /// </summary>
        internal static string txtSendToTray {
            get {
                return ResourceManager.GetString("txtSendToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Digite um CPF!.
        /// </summary>
        internal static string txtTypeCpf {
            get {
                return ResourceManager.GetString("txtTypeCpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Digite um nome!.
        /// </summary>
        internal static string txtTypeName {
            get {
                return ResourceManager.GetString("txtTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Digite o número!.
        /// </summary>
        internal static string txtTypeNumber {
            get {
                return ResourceManager.GetString("txtTypeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Digite um telefone!.
        /// </summary>
        internal static string txtTypePhone {
            get {
                return ResourceManager.GetString("txtTypePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Digite uma matricula!.
        /// </summary>
        internal static string txtTypeRegistration {
            get {
                return ResourceManager.GetString("txtTypeRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap utensils_solid {
            get {
                object obj = ResourceManager.GetObject("utensils-solid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap valor {
            get {
                object obj = ResourceManager.GetObject("valor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
